### ISSUE TITLE
Importing custompathed NPV .ent is errored

### ISSUE THREAD

**Issue by nananarc** [WolvenKit/Cyberpunk-Blender-add-on#147]
I'm trying to import my custom entity but blender give this error message and nothing else happens:

`Python: Traceback (most recent call last):
  File "C:\Users\dahli\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\i_scene_cp77_gltf\__init__.py", line 1331, in execute
    importEnt( bob, apps, excluded,self.with_materials, self.include_collisions, self.include_phys, self.include_entCollider, inColl, self.remap_depot)
  File "C:\Users\dahli\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\i_scene_cp77_gltf\importers\entity_import.py", line 712, in importEnt
    if app_name:
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'app_name' where it is not associated with a value`

What I have tried:
- Input correct app name
- Having custom app name
- Changing custom app name to "default"
- Regenerate depot with newest WK
- Re-export all needed materials for the NPV with newest WK
- Older version of plugin with older compatible version of WK and Blender

Version info:
- Blender 4.1
- WK 8.13 nightly (April 25)
- Plugin 1.5.5.2

Mana said this is likely a code problem so I figure it should be logged here

**Comment by Simarilius-uk** [comment]
Seems to work fine with basegame ents here, can you send me your wkit project? (discord dm would work)

**Comment by Simarilius-uk** [comment]
Tracked it down to having a folder called \[working] NA\ in the project path, reproducable here. Needs fixing.
