### ISSUE TITLE
Blender Python Error:  KeyError: 'disable_bone_shape'

### ISSUE THREAD

**Issue by hestenet** [WolvenKit/Cyberpunk-Blender-add-on#174]
Just installed Blender and Cyberpunk-Blender-add-on for the first time. 

When attempting to use the File - Import - Cyberpunk GLTF to import a gltf or glb file exported from wolvenkit (used an unmodified file to test): 

I get the following error:

```
Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\__init__.py", line 1470, in execute
    CP77GLBimport(self, self.exclude_unused_mats, self.image_format, self.with_materials, self.filepath, self.hide_armatures, self.import_garmentsupport, self.files, self.directory, self.appearances, props.remap_depot)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\importers\import_with_materials.py", line 51, in CP77GLBimport
    BlenderGlTF.create(gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 38, in create
    BlenderGlTF._create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 45, in _create
    BlenderScene.create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 35, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 47, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 33, in create_vnode
    obj = BlenderNode.create_object(gltf, vnode_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 82, in create_object
    BlenderNode.armature_display(gltf, obj)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 133, in armature_display
    if gltf.import_settings['disable_bone_shape'] is True:
       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'disable_bone_shape'

```

**Comment by Vallereya** [comment]
Did you happen to find a workaround to this one?

**Comment by Simarilius-uk** [comment]
Thats from using 1.5.5 in 4.2 isnt it?

**Comment by Vallereya** [comment]
Yes it is

**Comment by DoctorPresto** [comment]
Sorry guys, have been hit with a bunch of stuff irl. I have quite a bit to push, including this fix. I should be able to finally get this all in this week

**Comment by MatthiasVanMeerbeek** [comment]
A temporary solution is to **rollback Blender** to version **4.0.2** and then you can use the latest addon version (1.5.5.2) without running into issues. 

I was originally on **Blender 4.4.2** but that didn't work with any version of the addons I tried:
- 1.5.5.2
- 1.5.4.1
- v1.5.3

To do a rollback to or install an older version of Blender:
- Blender official website:
    - Go to the official "previous versions" page: https://www.blender.org/download/previous-versions/
    - Click on "[Download any Blender](https://download.blender.org/release/)"
    - Scroll down and click on "[Blender4.0/](https://download.blender.org/release/Blender4.0/)"
    - Choose a version for your operating system that starts with "blender-4.0.2"
    - Download and install that version of Blender
- Blender on Steam: 
    - Find Blender in your Steam library
    - Right click on Blender
    - Click on "Properties" > "Betas"
    - Open the dropdown box next to "Beta Participation" and choose "v4.0 - Stable"
    - Close the window and let Steam handle the download and installation

(Wolvenkit 8.14.0)
