### ISSUE TITLE
Errors importing parallax screen

### ISSUE THREAD

**Issue by Simarilius-uk** [WolvenKit/Cyberpunk-Blender-add-on#177]
\base\environment\decoration\electronics\hardware\server_entropy\server_entropy_a.glb
-------------------- Beginning Cyberpunk Model Import --------------------

Importing: server_entropy_a.glb with materials
Appearances to Import: default

Processing: server_entropy_a.Material.json
Building shaders
Traceback (most recent call last):
  File "C:\Users\johnc\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\importers\import_with_materials.py", line 264, in import_mats
    bpymat = Builder.create(mats, index)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johnc\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\main\setup.py", line 173, in create
    parallaxScreenTransparent.create(rawMat["Data"],bpyMat)
  File "C:\Users\johnc\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\i_scene_cp77_gltf\material_types\parallaxscreentransparent.py", line 806, in create
    l3Group = bpy.data.node_groups['l3_ps_t']
              ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "l3_ps_t" not found'
None


Material Setup Failed on: Screen_UI_default

Looks like it just needs an if to check something exists

**Comment by Simarilius-uk** [comment]
Not getting this testing this file now, seems to have fixed itself.
