### ISSUE TITLE
"Transfer Weights" fails if meshes in source armature are hidden

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/Cyberpunk-Blender-add-on#94]
Blender 3.6.2 with 1.5.1 stable

Maybe you fixed this already, in this case, feel free to close it. 

```
Traceback (most recent call last):
  File "C:\Users\manav\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\__init__.py", line 752, in execute
    result = trans_weights(self, context)
  File "C:\Users\manav\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\main\meshtools.py", line 102, in trans_weights
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
Error: Python: Traceback (most recent call last):
  File "C:\Users\manav\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\__init__.py", line 752, in execute
    result = trans_weights(self, context)
  File "C:\Users\manav\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\main\meshtools.py", line 102, in trans_weights
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object

```

**Comment by DoctorPresto** [comment]
is the desired behaviour for the weights of the hidden meshes to get transferred as well, or for the hidden meshes to be ignored?

**Comment by manavortex** [comment]
wish I knew 😅 ignored?
